Repository BK-marriott/server, pull requests merged in 2025-01, with the labels that each got.

#2 [#1] 유레카 서버 구현 완료
  com.bkmarriott.eureka/.gitattributes
  com.bkmarriott.eureka/.gitignore
  com.bkmarriott.eureka/build.gradle
  com.bkmarriott.eureka/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.eureka/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.eureka/gradlew
  com.bkmarriott.eureka/gradlew.bat
  com.bkmarriott.eureka/settings.gradle
  com.bkmarriott.eureka/src/main/java/com/bkmarriott/eureka/EurekaApplication.java
  com.bkmarriott.eureka/src/main/resources/application.yml
  com.bkmarriott.eureka/src/test/java/com/bkmarriott/eureka/EurekaApplicationTests.java
Labels: 기능 개발

#4 [#3] 게이트웨이 서비스 구현
  com.bkmarriott.gateway/.gitattributes
  com.bkmarriott.gateway/.gitignore
  com.bkmarriott.gateway/build.gradle
  com.bkmarriott.gateway/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.gateway/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.gateway/gradlew
  com.bkmarriott.gateway/gradlew.bat
  com.bkmarriott.gateway/settings.gradle
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/GatewayApplication.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/exception/ErrorResponse.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/exception/FilterExceptionHandler.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/exception/exceptions/InvalidTokenException.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/exception/exceptions/UnAuthenticatedException.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/exception/messages/InvalidTokenErrorMessage.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/filter/GlobalPreRequestFilter.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/filter/GlobalPreResponseFilter.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/filter/auth/AccessAuthorizationFilter.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/filter/auth/AccessTokenAuthenticationFilter.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/util/RolePermission.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/util/dategnerator/AccessTokenDateGenerator.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/util/dategnerator/DateGenerator.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/util/tokenprovider/AccessTokenProvider.java
  com.bkmarriott.gateway/src/main/java/com/bkmarriott/gateway/util/tokenprovider/Actor.java
  com.bkmarriott.gateway/src/main/resources/application.yml
  com.bkmarriott.gateway/src/test/java/com/bkmarriott/gateway/GatewayApplicationTests.java
Labels: 기능 개발

#13 [#9] 호텔 검색 기능 구현, Jacoco 환경 구축 및 테스트
  com.bkmarriott.hotel/.gitattributes
  com.bkmarriott.hotel/.gitignore
  com.bkmarriott.hotel/build.gradle
  com.bkmarriott.hotel/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.hotel/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.hotel/gradlew
  com.bkmarriott.hotel/gradlew.bat
  com.bkmarriott.hotel/settings.gradle
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/HotelApplication.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/dto/HotelSearchResponseDto.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/outputport/ChargeOutputPort.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/outputport/HotelQueryOutputPort.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/service/HotelService.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/domain/Hotel.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/config/FeignConfig.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/config/QuerydslConfig.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/adapter/ChargeFeignClientAdapter.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/client/ChargeClient.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/dto/RoomChargeResponse.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/dto/RoomType.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/adapter/HotelQueryAdapter.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/entity/BaseEntity.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/entity/HotelEntity.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/mapper/HotelEntityMapper.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/repository/HotelQueryRepository.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/exception/CustomException.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/exception/ExceptionType.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/exception/GlobalExceptionHandler.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/exception/RestApiException.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/config/WebConfig.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/controller/HotelController.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/dto/request/HotelSearchRequest.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/dto/response/HotelSearchResponse.java
  com.bkmarriott.hotel/src/main/resources/application.yml
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/HotelApplicationTests.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/application/service/HotelServiceTest.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/infrastructure/feignClient/adapter/ChargeFeignClientAdapterTest.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/presentation/rest/controller/HotelControllerTest.java
Labels: 기능 개발

#14 [#11] 객실 요금 생성, 수정, 조회 API
  .gitignore
  com.bkmarriott.charge/.gitattributes
  com.bkmarriott.charge/.gitignore
  com.bkmarriott.charge/build.gradle
  com.bkmarriott.charge/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.charge/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.charge/gradlew
  com.bkmarriott.charge/gradlew.bat
  com.bkmarriott.charge/settings.gradle
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/ChargeApplication.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/application/exception/RoomChargeDuplicatedException.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/application/exception/RoomChargeErrorMessage.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/application/exception/RoomChargeNotFoundException.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/application/outputport/RoomChargeOutputPort.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/application/service/RoomChargeService.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/domain/RoomCharge.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/domain/vo/RoomChargeForCreate.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/domain/vo/RoomChargeId.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/domain/vo/RoomType.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/adapter/RoomChargeAdapter.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/entity/BaseEntity.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/entity/RoomChargeEntity.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/entity/RoomChargeEntityId.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/entity/RoomEntityType.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/infrastructure/persistence/repository/RoomChargeRepository.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/presentation/rest/controller/RoomChargeController.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/presentation/rest/dto/CreateRoomCharge.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/presentation/rest/dto/FindRoomCharge.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/presentation/rest/dto/RoomChargeResponse.java
  com.bkmarriott.charge/src/main/java/com/bkmarriott/charge/presentation/rest/exception/GlobalExceptionHandler.java
  com.bkmarriott.charge/src/main/resources/application.yml
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/ChargeApplicationTests.java
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/application/service/RoomChargeServiceTest.java
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/domain/RoomChargeTest.java
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/infrastructure/persistence/adapter/RoomChargeAdapterTest.java
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/infrastructure/persistence/config/RepositoryTest.java
  com.bkmarriott.charge/src/test/java/com/bkmarriott/charge/presentation/rest/controller/RoomChargeControllerTest.java
Labels: 기능 개발

#21 [#19] 예약 가능 객실 수 기능 구현 및 테스트
  com.bkmarriott.reservation/.gitattributes
  com.bkmarriott.reservation/.gitignore
  com.bkmarriott.reservation/build.gradle
  com.bkmarriott.reservation/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.reservation/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.reservation/gradlew
  com.bkmarriott.reservation/gradlew.bat
  com.bkmarriott.reservation/settings.gradle
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/ReservationApplication.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/InventoryUpdateFailureException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/RoomTypeInventoryEntityException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/InventoryCommandOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/InventoryQueryOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/ReservationQueryOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Inventory.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Reservation.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/ReservationStatus.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/RoomType.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/config/QueryDslConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryCommandAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryQueryAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/ReservationQueryAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/BaseEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntityStatus.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomEntityType.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomTypeInventoryEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomTypeInventoryId.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryQueryDslRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/ReservationRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryCommandController.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryQueryController.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/command/InventoryModification.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/query/InventoryQuery.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/exception/GlobalExceptionControllerAdvice.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/exception/InvalidAccessException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/exception/ResourceNotFoundException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/util/reponse/ApiResponse.java
  com.bkmarriott.reservation/src/main/resources/application-dev.yml
  com.bkmarriott.reservation/src/main/resources/application.yml
  com.bkmarriott.reservation/src/main/resources/data.sql
  com.bkmarriott.reservation/src/main/resources/schema.sql
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/ReservationApplicationTests.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/http/Inventory.http
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/adapter/InventoryCommandAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/config/RepositoryTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryCommandControllerTest.java
Labels: 기능 개발

#17 [#8] 쿠폰 단건 조회(검증) API 구현
  com.bkmarriott.coupon/.gitignore
  com.bkmarriott.coupon/build.gradle
  com.bkmarriott.coupon/gradle/wrapper/gradle-wrapper.jar
  com.bkmarriott.coupon/gradle/wrapper/gradle-wrapper.properties
  com.bkmarriott.coupon/gradlew
  com.bkmarriott.coupon/gradlew.bat
  com.bkmarriott.coupon/settings.gradle
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/CouponApplication.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/MemberCouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/Coupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/CouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/MemberCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/vo/CouponPolicyType.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/MemberCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/BaseEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntityType.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/MemberCouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/MemberCouponRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponQueryController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/response/GetMemberCouponResponse.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/DefaultException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/ExceptionStatus.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/GlobalExceptionHandler.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/MemberCouponNotFoundException.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/CouponApplicationTests.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/MemberCouponAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/config/RepositoryTest.java
Labels: 기능 개발

#29 [#22] 쿠폰 발급 이벤트 처리 기능 구현 및 코드 동기화
  com.bkmarriott.coupon/build.gradle
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/exception/EventDuplicateException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/CouponEventLogOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/CouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/MemberCouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/UserCouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/CouponEventService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/CouponService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/UserCouponService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/Coupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/CouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/MemberCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/UserCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/event/CouponIssuanceEvent.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/event/DomainEvent.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/event/DomainEventEnvelop.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/vo/UserCouponForIssue.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/CouponCommandPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/CouponEventLogPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/MemberCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponCommandPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponIssuanceEventLogEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntityType.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/UserCouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/CouponIssuanceEventLogRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/CouponRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/MemberCouponRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/UserCouponRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/event/config/KafkaConsumerConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/event/subscriber/CouponIssuanceEventSubscriber.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/event/util/CouponIssuanceEventDeserializer.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponQueryController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/response/GetMemberCouponResponse.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/ExceptionStatus.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/MemberCouponNotFoundException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/UserCouponNotFoundException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/ouputport/UserCouponQueryOutport.java
  com.bkmarriott.coupon/src/main/resources/application-test.yml
  com.bkmarriott.coupon/src/main/resources/application.yml
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/CouponPolicyTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/CouponTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/UserCouponTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/config/PersistenceTestConfig.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/config/RepositoryTest.java
Labels: 기능 개발, 수정

#31 [#28] 사용자 쿠폰 사용 API 구현
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/UserCouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/UserCouponService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/UserCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponCommandPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/UserCouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/CouponPolicyRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponCommandController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponQueryController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/response/GetUserCouponResponse.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/response/PatchUserCouponResponse.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
Labels: 기능 개발

#36 [#24] 예약 기능 구현
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/dto/InventoryQueryResponseDto.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/PaymentFailureException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/RoomInventoryQuantityException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/CouponOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/InventoryQueryOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/PaymentOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/ReservationCommandOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Inventory.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Reservation.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/InventoryQuantity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/ReservationForCreate.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/CouponAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/PaymentAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/dto/Payment.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/dto/PaymentStatus.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryQueryAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/ReservationCommandAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/config/QueryDslConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntityStatus.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomTypeInventoryEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryQueryDslRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryQueryController.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/ReservationController.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/auth/Actor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/auth/Role.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/command/ReservationModification.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/query/InventoryQuery.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/util/auth/LoginActor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/util/auth/LoginActorArgumentResolver.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/domain/ReservationTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryCommandAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryQueryAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/ReservationCommandAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/config/PersistenceTestConfig.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/config/RepositoryTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryQueryControllerTest.java
Labels: 기능 개발

#39 [#27] 예약 및 결제 기능 구현 및 테스트 코드 작성 (#34)
  com.bkmarriott.reservation/build.gradle
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/NoAvailableRoomsException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/PaymentException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/exception/ReservationProcessingException.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/InventoryQueryOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/ReservationCommandOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/feign/CouponOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/feign/PaymentOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationProcessingService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Inventory.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Reservation.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/InventoryQuery.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/Payment.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/PaymentForCreate.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/ReservationForCreate.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/CouponFeignClientAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/PaymentFeignClientAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/client/CouponClient.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/client/PaymentClient.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/config/FeignConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/dto/CouponDto.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/dto/PaymentDto.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/dto/PaymentRequestDto.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryQueryAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/ReservationCommandAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/ReservationEntityStatus.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomTypeInventoryEntity.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryQueryDslRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/config/RestConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/ReservationCommandController.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/auth/Actor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/auth/Role.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/dto/command/ReservationCreationDTO.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/util/auth/LoginActor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/presentation/rest/util/auth/LoginActorArgumentResolver.java
  com.bkmarriott.reservation/src/main/resources/data.sql
  com.bkmarriott.reservation/src/main/resources/schema.sql
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationProcessingServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/domain/InventoryTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/domain/vo/InventoryQueryTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/domain/vo/PaymentForCreateTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/domain/vo/ReservationForCreateTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/adapter/CouponFeignClientAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/adapter/PaymentForCreateFeignClientAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/adapter/ReservationCommandAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/config/PersistenceTestConfig.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/InventoryCommandControllerTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/rest/controller/ReservationCommandControllerTest.java
Labels: 기능 개발

#32 [#30] 쿠폰 발급 이벤트 처리 기능 테스트 코드 작성
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/CouponEventLogOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/CouponEventService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/UserCouponService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/UserCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/CouponCommandPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/CouponEventLogPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/config/PersistenceConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/UserCouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/CouponPolicyRepository.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/CouponEventServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/CouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/UserCouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/CouponCommandPersistenceAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/CouponEventLogPersistenceAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponCommandPersistenceAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/config/PersistenceTestConfig.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/config/RepositoryTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/presentation/event/subscriber/CouponIssuanceEventSubscriberTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/presentation/rest/controller/CouponCommandControllerTest.java
Labels: 기능 개발, 테스트

#45 [#44] Reservation FeignClient 수정
  com.bkmarriott.reservation/build.gradle
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/client/CouponClient.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/client/PaymentClient.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/config/FeignOkHttpConfiguration.java
Labels: 수정

#40 [#33] 사용자 쿠폰 사용 취소(롤백) 기능 구현
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/outputport/UserCouponOutputPort.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/application/service/UserCouponService.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/UserCoupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponCommandPersistenceAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/UserCouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/exception/CouponNotSpentException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/exception/UserCouponNotFoundException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponCommandController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/ExceptionStatus.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/UserCouponNotFoundException.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/UserCouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
Labels: 기능 개발, 테스트

#50 [#49] 예약 선점 기능 구현 및 리팩토링
  com.bkmarriott.charge/src/main/resources/application-test.yml
  com.bkmarriott.payment/src/main/resources/application-test.yml
  com.bkmarriott.reservation/build.gradle
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/cache/InventoryCacheOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/feign/PaymentOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationProcessingService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/vo/InventoryQuery.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/cache/adapter/InventoryCacheAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/cache/config/RedisConfig.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/cache/util/RedisKeyFactory.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/PaymentFeignClientAdapter.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/client/PaymentClient.java
  com.bkmarriott.reservation/src/main/resources/application-dev.yml
  com.bkmarriott.reservation/src/main/resources/application-test.yml
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationProcessingServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/application/service/ReservationServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/ChargeFeignClientAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/CouponFeignClientAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/feignClient/adapter/PaymentFeignClientAdapterTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/ReservationCommandAdapterTest.java
Labels: 기능 개발, 수정

#52 [#51] 인벤토리 예약 객실 수 업데이트 버그 수정 완료
  com.bkmarriott.payment/gradlew
  com.bkmarriott.payment/gradlew.bat
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/outputport/InventoryCommandOutputPort.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/application/service/InventoryService.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/domain/Inventory.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/adapter/InventoryCommandAdaptor.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/entity/RoomTypeInventoryId.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryQueryDslRepository.java
  com.bkmarriott.reservation/src/main/java/com/bkmarriott/reservationservice/reservation/infrastructure/persistence/repository/InventoryRepository.java
  com.bkmarriott.reservation/src/main/resources/data.sql
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/application/service/InventoryServiceTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/adapter/InventoryCommandAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/adapter/InventoryQueryAdaptorTest.java
  com.bkmarriott.reservation/src/test/java/com/bkmarriott/reservationservice/reservation/presentation/infrastructure/persistence/config/PersistenceTestConfig.java
Labels: 버그

#56 [#38] GitHub Actions를 이용한 배포 자동화 파이프라인 구성
  .github/workflows/github-actions.yml
  com.bkmarriott.auth/Dockerfile
  com.bkmarriott.charge/Dockerfile
  com.bkmarriott.coupon/Dockerfile
  com.bkmarriott.eureka/Dockerfile
  com.bkmarriott.gateway/Dockerfile
  com.bkmarriott.hotel/Dockerfile
  com.bkmarriott.payment/Dockerfile
  com.bkmarriott.promotion/Dockerfile
  com.bkmarriott.reservation/Dockerfile
Labels: 기능 개발

#59 [#23] 쿠폰 발급 이벤트 발행 로직 리팩토링
  com.bkmarriott.promotion/build.gradle
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/event/CouponIssuance.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/listener/CouponExternalEventMessageListener.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/listener/CouponExternalEventRecordListener.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/CouponExternalEventReader.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/CouponExternalEventRecorder.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/CouponExternalMessageSender.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/CouponOutputPort.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/PromotionReader.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/outputport/TimeAttackCouponIssuer.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/schedule/config/SchedulingConfig.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/schedule/sceduler/CouponIssuancePublishScheduler.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/service/ApplicationEventPublishService.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/service/CouponExternalEventSendService.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/service/PromotionService.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/service/TimeAttackCouponIssuanceService.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/application/service/TimeAttackCouponService.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/cache/adapter/TimeAttackCouponCacheAdapter.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/event/adapter/CouponEventSendAdapter.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/event/publisher/CouponIssuanceEventPublisher.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/persistence/adapter/CouponEventPersistenceAdapter.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/persistence/adapter/PromotionPersistenceAdapter.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/persistence/entity/CouponIssuanceOutboxEntity.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/persistence/repository/CouponIssuanceOutboxRepository.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/persistence/util/EventConverter.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/infrastructure/schedule/scheduler/CouponIssuancePublishScheduler.java
  com.bkmarriott.promotion/src/main/java/com/bkmarriott/promotion/presentation/rest/controller/TimeAttackCouponController.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/listener/CouponExternalEventMessageListenerTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/listener/CouponExternalEventRecordListenerTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/service/ApplicationEventPublishServiceTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/service/CouponExternalEventSendServiceTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/service/PromotionServiceTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/application/service/TimeAttackCouponIssuanceServiceTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/infrastructure/persistence/adapter/CouponEventPersistenceAdapterTest.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/infrastructure/persistence/config/PersistenceTestConfig.java
  com.bkmarriott.promotion/src/test/java/com/bkmarriott/promotion/presentation/rest/controller/TimeAttackCouponControllerTest.java
Labels: 기능 개발, 성능 개선

#60 [#55] 호텔 검색 리팩토링
  com.bkmarriott.hotel/build.gradle
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/dto/HotelSearchResponseDto.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/outputport/ChargeOutputPort.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/service/HotelQueryService.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/application/service/HotelService.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/domain/Hotel.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/adapter/ChargeFeignClientAdapter.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/client/ChargeClient.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/config/FeignConfig.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/feignClient/dto/RoomChargeResponse.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/config/QuerydslConfig.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/infrastructure/persistence/repository/HotelQueryRepository.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/controller/HotelQueryController.java
  com.bkmarriott.hotel/src/main/java/com/bkmarriott/hotel/presentation/rest/dto/response/HotelSearchResponse.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/application/service/HotelQueryServiceTest.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/application/service/HotelServiceTest.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/infrastructure/feignClient/adapter/ChargeFeignClientAdapterTest.java
  com.bkmarriott.hotel/src/test/java/com/bkmarriott/hotel/presentation/rest/controller/HotelQueryControllerTest.java
Labels: 수정

#69 [#61] 회원별 쿠폰 목록 조회 기능 구현
  com.bkmarriott.coupon/build.gradle
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/adapter/UserCouponQueryAdapter.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/repository/UserCouponRepository.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/config/RestConfig.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/controller/CouponQueryController.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/auth/Actor.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/auth/Role.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/dto/response/GetUserCouponListResponse.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/ExceptionStatus.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/UserIdMissingException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/exception/UserRoleMissingException.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/ouputport/UserCouponQueryOutport.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/util/LoginActor.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/presentation/rest/util/LoginActorArgumentResolver.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/UserCouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/presentation/rest/controller/CouponCommandControllerTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/presentation/rest/controller/CouponQueryControllerTest.java
Labels: 기능 개발

#64 [#63] 쿠폰 사용 기간 정책 도메인 클래스 리팩토링
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/Coupon.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/CouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/AfterCouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/CouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/CouponPolicyFactory.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/FixedCouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/LegacyCouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/domain/couponpolicy/MixedCouponPolicy.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponEntity.java
  com.bkmarriott.coupon/src/main/java/com/bkmarriott/coupon/infrastructure/persistence/entity/CouponPolicyEntity.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/CouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/application/service/UserCouponServiceTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/CouponPolicyTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/CouponTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/UserCouponTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/domain/couponpolicy/CouponPolicyFactoryTest.java
  com.bkmarriott.coupon/src/test/java/com/bkmarriott/coupon/persistence/adapter/UserCouponAdapterTest.java
Labels: 수정
